### ISSUE TITLE
Suggestions on making it easier to use..

### ISSUE THREAD

**Issue by Shadowblitz16** [philbgarner/SkinUI#1]
I just saw this library and I have the following suggestions that might make easier to use..

instead of doing..
```
  -- Add a new window named 'win1' to the root node.
  skinui:add(skinui.Window:new(id, w, h, theme))
```

why not do a more intermediate approach?..
`if skinui:<WidgetName>(parent, id, x, y, w, h, theme) == skinui.<EventType> then end`

and instead of multipule sized buttons why not specify a size?
`if skinui:button(parent, id, x, y, w, h, theme)`

**Comment by philbgarner** [comment]
Sorry for the delay on responding to this, I have been busy with other projects.  Is this a change you would feel comfortable making? I'd be happy to merge a pull request.  Thanks for your feedback, immediate mode is a wonderful idea.

**Comment by Shadowblitz16** [comment]
I sadly do not use love2d anymore. I should probably close this.
